### ISSUE TITLE
Linux: Because who needs other OSes?

### ISSUE THREAD

**Issue by BIRSAx2** [jacopo-angeli/RforCandD-P#1]
Love the commitment to Linux. Really, I do. But any chance we could get support for those "other" operating systems? Or should we just convert and bow to the penguin overlords? 🐧

```
Compile and run
Linux: Use ./compile.sh and ./run.sh.
Others: Install Linux and try (1).
```

**Comment by jacopo-angeli** [comment]
Dear BIRSAx2, 

We truly appreciate your interest in our product, but, after an incredibly intense (yet surprisingly brief) internal discussion on the matter, we have decided to maintain this project exclusively on the Linux operating system. 

We are confident that the vast software pool available on those "other" OSes is already abundant with... shall we say, varying levels of quality. We humbly believe that our application would certainly neither elevate nor diminish the average standard, and as such, we find it most fitting to keep our project in the hands of the discerning Linux community.

Thank you for your understanding.
